export type Theme = {
  isDark: boolean;
  bg: string;
  card: string;
  text: string;
  textSecondary: string;
  regionBorder: string;
  innerBorder: string;
  markColor: string;
  accent: string;
  onAccent: string;
  highlight: string;
  onHighlight: string;
  shadow: string;
  spacingMd: number;
  spacingLg: number;
  spacingXl: number;
  radiusMd: number;
  fontSizeSm: number;
  fontSizeMd: number;
  fontSizeLg: number;
  fontWeightSemibold: '600';
  cellSize: number;
};
