[colors.roles]
text = "#bfbdb6"
textSecondary = "#bfbdb699"
background = "#0b0e14"
surface = "#bfbdb60d"
border = "#bfbdb638"
puzzleBorder = "#bfbdb6"
puzzleInnerBorder = "#bfbdb638"
blue = "#53bdfa"
red = "#ea6c73"
green = "#7fd962"
yellow = "#f9af4f"

[colors.regions]
red = "#ea6c73"
green = "#7fd962"
yellow = "#f9af4f"
blue = "#53bdfa"
magenta = "#cda1fa"
cyan = "#90e1c6"
redBright = "#f07178"
greenBright = "#aad94c"
yellowBright = "#ffb454"
blueBright = "#59c2ff"
magentaBright = "#d2a6ff"
cyanBright = "#95e6cb"
