[colors.roles]
text = "#5c6166"
textSecondary = "#5c6166b3"
background = "#f8f9fa"
surface = "#f8f9fa"
border = "#5c61662e"
puzzleBorder = "#5c6166"
puzzleInnerBorder = "#5c6166b3"
blue = "#3199e1"
red = "#ea6c6d"
green = "#6cbf43"
yellow = "#eca944"

[colors.regions]
red = "#ea6c6d"
green = "#6cbf43"
yellow = "#eca944"
blue = "#3199e1"
magenta = "#9e75c7"
cyan = "#46ba94"
redBright = "#f07171"
greenBright = "#86b300"
yellowBright = "#f2ae49"
blueBright = "#399ee6"
magentaBright = "#a37acc"
cyanBright = "#4cbf99"
