[colors.roles]
text = "#cdd6f4"
textSecondary = "#cdd6f499"
background = "#1e1e2e"
surface = "#cdd6f40d"
border = "#cdd6f438"
puzzleBorder = "#cdd6f4"
puzzleInnerBorder = "#cdd6f438"
blue = "#89b4fa"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"

[colors.regions]
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
redBright = "#f37799"
greenBright = "#89d88b"
yellowBright = "#ebd391"
blueBright = "#74a8fc"
magentaBright = "#f2aede"
cyanBright = "#6bd7ca"
