[colors.roles]
text = "#4c4f69"
textSecondary = "#4c4f6999"
background = "#eff1f5"
surface = "#4c4f690d"
border = "#4c4f6938"
puzzleBorder = "#4c4f69"
puzzleInnerBorder = "#4c4f6938"
blue = "#1e66f5"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"

[colors.regions]
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
redBright = "#de293e"
greenBright = "#49af3d"
yellowBright = "#eea02d"
blueBright = "#456eff"
magentaBright = "#fe85d8"
cyanBright = "#2d9fa8"
