[colors.roles]
text = "#d3c6aa"
textSecondary = "#d3c6aa99"
background = "#2d353b"
surface = "#d3c6aa0d"
border = "#d3c6aa38"
puzzleBorder = "#d3c6aa"
puzzleInnerBorder = "#d3c6aa38"
blue = "#7fbbb3"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"

[colors.regions]
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
redBright = "#e67e80"
greenBright = "#a7c080"
yellowBright = "#dbbc7f"
blueBright = "#7fbbb3"
magentaBright = "#d699b6"
cyanBright = "#83c092"
