[colors.roles]
text = "#1f2328"
textSecondary = "#1f2328b3"
background = "#f6f8fa"
surface = "#f6f8fa"
border = "#1f23282e"
puzzleBorder = "#1f2328"
puzzleInnerBorder = "#1f2328b3"
blue = "#0969da"
red = "#cf222e"
green = "#116329"
yellow = "#4d2d00"

[colors.regions]
red = "#cf222e"
green = "#116329"
yellow = "#4d2d00"
blue = "#0969da"
magenta = "#8250df"
cyan = "#1b7c83"
redBright = "#a40e26"
greenBright = "#1a7f37"
yellowBright = "#633c01"
blueBright = "#218bff"
magentaBright = "#a475f9"
cyanBright = "#3192aa"
