[colors.roles]
text = "#3c3836"
textSecondary = "#3c3836b3"
background = "#fbf1c7"
surface = "#fbf1c7"
border = "#3c38362e"
puzzleBorder = "#3c3836"
puzzleInnerBorder = "#3c3836b3"
blue = "#458588"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"

[colors.regions]
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
redBright = "#9d0006"
greenBright = "#79740e"
yellowBright = "#b57614"
blueBright = "#076678"
magentaBright = "#8f3f71"
cyanBright = "#427b58"
