[colors.roles]
text = "#33374c"
textSecondary = "#33374cb3"
background = "#e8e9ec"
surface = "#e8e9ec"
border = "#33374c2e"
puzzleBorder = "#33374c"
puzzleInnerBorder = "#33374cb3"
blue = "#2d539e"
red = "#cc517a"
green = "#668e3d"
yellow = "#c57339"

[colors.regions]
red = "#cc517a"
green = "#668e3d"
yellow = "#c57339"
blue = "#2d539e"
magenta = "#7759b4"
cyan = "#3f83a6"
redBright = "#cc3768"
greenBright = "#598030"
yellowBright = "#b6662d"
blueBright = "#22478e"
magentaBright = "#6845ad"
cyanBright = "#327698"
