[colors.roles]
text = "#c6c8d1"
textSecondary = "#c6c8d199"
background = "#161821"
surface = "#c6c8d10d"
border = "#c6c8d138"
puzzleBorder = "#c6c8d1"
puzzleInnerBorder = "#c6c8d138"
blue = "#84a0c6"
red = "#e27878"
green = "#b4be82"
yellow = "#e2a478"

[colors.regions]
red = "#e27878"
green = "#b4be82"
yellow = "#e2a478"
blue = "#84a0c6"
magenta = "#a093c7"
cyan = "#89b8c2"
redBright = "#e98989"
greenBright = "#c0ca8e"
yellowBright = "#e9b189"
blueBright = "#91acd1"
magentaBright = "#ada0d3"
cyanBright = "#95c4ce"
