[colors.roles]
text = "#cdcecf"
textSecondary = "#cdcecf99"
background = "#192330"
surface = "#cdcecf0d"
border = "#cdcecf38"
puzzleBorder = "#cdcecf"
puzzleInnerBorder = "#cdcecf38"
blue = "#719cd6"
red = "#c94f6d"
green = "#81b29a"
yellow = "#dbc074"

[colors.regions]
red = "#c94f6d"
green = "#81b29a"
yellow = "#dbc074"
blue = "#719cd6"
magenta = "#9d79d6"
cyan = "#63cdcf"
redBright = "#d16983"
greenBright = "#8ebaa4"
yellowBright = "#e0c989"
blueBright = "#86abdc"
magentaBright = "#baa1e2"
cyanBright = "#7ad5d6"
