[colors.roles]
text = "#3d2b5a"
textSecondary = "#3d2b5a99"
background = "#f6f2ee"
surface = "#3d2b5a0d"
border = "#3d2b5a38"
puzzleBorder = "#3d2b5a"
puzzleInnerBorder = "#3d2b5a38"
blue = "#2848a9"
red = "#a5222f"
green = "#396847"
yellow = "#ac5402"

[colors.regions]
red = "#a5222f"
green = "#396847"
yellow = "#ac5402"
blue = "#2848a9"
magenta = "#6e33ce"
cyan = "#287980"
redBright = "#b3434e"
greenBright = "#577f63"
yellowBright = "#b86e28"
blueBright = "#4863b6"
magentaBright = "#8452d5"
cyanBright = "#488d93"
