[colors.roles]
text = "#cccccc"
textSecondary = "#cccccc99"
background = "#011627"
surface = "#cccccc0d"
border = "#cccccc38"
puzzleBorder = "#cccccc"
puzzleInnerBorder = "#cccccc38"
blue = "#82aaff"
red = "#ef5350"
green = "#22da6e"
yellow = "#c5e478"

[colors.regions]
red = "#ef5350"
green = "#22da6e"
yellow = "#c5e478"
blue = "#82aaff"
magenta = "#c792ea"
cyan = "#21c7a8"
redBright = "#ef5350"
greenBright = "#22da6e"
yellowBright = "#ffeb95"
blueBright = "#82aaff"
magentaBright = "#c792ea"
cyanBright = "#7fdbca"
