[colors.roles]
text = "#403f53"
textSecondary = "#403f53b3"
background = "#f6f6f6"
surface = "#f6f6f6"
border = "#403f532e"
puzzleBorder = "#403f53"
puzzleInnerBorder = "#403f53b3"
blue = "#288ed7"
red = "#de3d3b"
green = "#08916a"
yellow = "#e0af02"

[colors.regions]
red = "#de3d3b"
green = "#08916a"
yellow = "#e0af02"
blue = "#288ed7"
magenta = "#d6438a"
cyan = "#2aa298"
redBright = "#de3d3b"
greenBright = "#08916a"
yellowBright = "#daaa01"
blueBright = "#288ed7"
magentaBright = "#d6438a"
cyanBright = "#2aa298"
