[colors.roles]
text = "#2a2b33"
textSecondary = "#2a2b33b3"
background = "#f8f8f8"
surface = "#f8f8f8"
border = "#2a2b332e"
puzzleBorder = "#2a2b33"
puzzleInnerBorder = "#2a2b33b3"
blue = "#2f5af3"
red = "#de3d35"
green = "#3e953a"
yellow = "#d2b67b"

[colors.regions]
red = "#de3d35"
green = "#3e953a"
yellow = "#d2b67b"
blue = "#2f5af3"
magenta = "#a00095"
cyan = "#3e953a"
redBright = "#de3d35"
greenBright = "#3e953a"
yellowBright = "#d2b67b"
blueBright = "#2f5af3"
magentaBright = "#a00095"
cyanBright = "#3e953a"
