[colors.roles]
text = "#dcdfe4"
textSecondary = "#dcdfe499"
background = "#282c34"
surface = "#dcdfe40d"
border = "#dcdfe438"
puzzleBorder = "#dcdfe4"
puzzleInnerBorder = "#dcdfe438"
blue = "#61afef"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"

[colors.regions]
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
redBright = "#e06c75"
greenBright = "#98c379"
yellowBright = "#e5c07b"
blueBright = "#61afef"
magentaBright = "#c678dd"
cyanBright = "#56b6c2"
