[colors.roles]
text = "#383a42"
textSecondary = "#383a42b3"
background = "#fafafa"
surface = "#fafafa"
border = "#383a422e"
puzzleBorder = "#383a42"
puzzleInnerBorder = "#383a42b3"
blue = "#0184bc"
red = "#e45649"
green = "#50a14f"
yellow = "#c18401"

[colors.regions]
red = "#e45649"
green = "#50a14f"
yellow = "#c18401"
blue = "#0184bc"
magenta = "#a626a4"
cyan = "#0997b3"
redBright = "#e06c75"
greenBright = "#98c379"
yellowBright = "#e5c07b"
blueBright = "#61afef"
magentaBright = "#c678dd"
cyanBright = "#56b6c2"
