[colors.roles]
text = "#abb2bf"
textSecondary = "#abb2bf99"
background = "#282c34"
surface = "#abb2bf0d"
border = "#abb2bf38"
puzzleBorder = "#abb2bf"
puzzleInnerBorder = "#abb2bf38"
blue = "#61afef"
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"

[colors.regions]
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
redBright = "#e06c75"
greenBright = "#98c379"
yellowBright = "#d19a66"
blueBright = "#61afef"
magentaBright = "#c678dd"
cyanBright = "#56b6c2"
