[colors.roles]
text = "#575279"
textSecondary = "#57527999"
background = "#fffaf3"
surface = "#5752790d"
border = "#57527938"
puzzleBorder = "#575279"
puzzleInnerBorder = "#57527938"
blue = "#56949f"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"

[colors.regions]
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
redBright = "#b4637a"
greenBright = "#286983"
yellowBright = "#ea9d34"
blueBright = "#56949f"
magentaBright = "#907aa9"
cyanBright = "#d7827e"
