[colors.roles]
text = "#e0def4"
textSecondary = "#e0def499"
background = "#1f1d2e"
surface = "#e0def40d"
border = "#e0def438"
puzzleBorder = "#e0def4"
puzzleInnerBorder = "#e0def438"
blue = "#9ccfd8"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"

[colors.regions]
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
redBright = "#eb6f92"
greenBright = "#31748f"
yellowBright = "#f6c177"
blueBright = "#9ccfd8"
magentaBright = "#c4a7e7"
cyanBright = "#ebbcba"
