[colors.roles]
text = "#d0d0d0"
textSecondary = "#d0d0d099"
background = "#3a3a3a"
surface = "#d0d0d00d"
border = "#d0d0d038"
puzzleBorder = "#d0d0d0"
puzzleInnerBorder = "#d0d0d038"
blue = "#85add4"
red = "#d68787"
green = "#5f865f"
yellow = "#d8af5f"

[colors.regions]
red = "#d68787"
green = "#5f865f"
yellow = "#d8af5f"
blue = "#85add4"
magenta = "#d7afaf"
cyan = "#87afaf"
redBright = "#d75f87"
greenBright = "#87af87"
yellowBright = "#ffd787"
blueBright = "#add4fb"
magentaBright = "#ffafaf"
cyanBright = "#87d7d7"
