[colors.roles]
text = "#4e4e4e"
textSecondary = "#4e4e4eb3"
background = "#dadada"
surface = "#dadada"
border = "#4e4e4e2e"
puzzleBorder = "#4e4e4e"
puzzleInnerBorder = "#4e4e4eb3"
blue = "#5f87ae"
red = "#af5f5f"
green = "#5f885f"
yellow = "#af8760"

[colors.regions]
red = "#af5f5f"
green = "#5f885f"
yellow = "#af8760"
blue = "#5f87ae"
magenta = "#875f87"
cyan = "#5f8787"
redBright = "#870100"
greenBright = "#005f00"
yellowBright = "#d8865f"
blueBright = "#0087af"
magentaBright = "#87025f"
cyanBright = "#008787"
