[colors.roles]
text = "#839496"
textSecondary = "#83949699"
background = "#002b36"
surface = "#8394960d"
border = "#83949638"
puzzleBorder = "#839496"
puzzleInnerBorder = "#83949638"
blue = "#268bd2"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"

[colors.regions]
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
redBright = "#cb4b16"
greenBright = "#586e75"
yellowBright = "#657b83"
blueBright = "#839496"
magentaBright = "#6c71c4"
cyanBright = "#93a1a1"
