[colors.roles]
text = "#657b83"
textSecondary = "#657b83b3"
background = "#fdf6e3"
surface = "#fdf6e3"
border = "#657b832e"
puzzleBorder = "#657b83"
puzzleInnerBorder = "#657b83b3"
blue = "#268bd2"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"

[colors.regions]
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
redBright = "#cb4b16"
greenBright = "#586e75"
yellowBright = "#657b83"
blueBright = "#839496"
magentaBright = "#6c71c4"
cyanBright = "#93a1a1"
