[colors.roles]
text = "#c0caf5"
textSecondary = "#c0caf599"
background = "#1a1b26"
surface = "#c0caf50d"
border = "#c0caf538"
puzzleBorder = "#c0caf5"
puzzleInnerBorder = "#c0caf538"
blue = "#7aa2f7"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"

[colors.regions]
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
redBright = "#f7768e"
greenBright = "#9ece6a"
yellowBright = "#e0af68"
blueBright = "#7aa2f7"
magentaBright = "#bb9af7"
cyanBright = "#7dcfff"
