[colors.roles]
text = "#3760bf"
textSecondary = "#3760bf99"
background = "#e1e2e7"
surface = "#3760bf0d"
border = "#3760bf38"
puzzleBorder = "#3760bf"
puzzleInnerBorder = "#3760bf38"
blue = "#2e7de9"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"

[colors.regions]
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
redBright = "#f52a65"
greenBright = "#587539"
yellowBright = "#8c6c3e"
blueBright = "#2e7de9"
magentaBright = "#9854f1"
cyanBright = "#007197"
