[colors.roles]
text = "#c0caf5"
textSecondary = "#c0caf599"
background = "#1a1b26"
surface = "#c0caf50d"
border = "#c0caf538"
puzzleBorder = "#c0caf5"
puzzleInnerBorder = "#c0caf538"
blue = "#7ba2f7"
red = "#f77890"
green = "#74dbcb"
yellow = "#e1b068"

[colors.regions]
red = "#f77890"
green = "#74dbcb"
yellow = "#e1b068"
blue = "#7ba2f7"
magenta = "#bb9bf7"
cyan = "#2bc4de"
redBright = "#f98ea0"
greenBright = "#6de5d3"
yellowBright = "#f2ba64"
blueBright = "#90affa"
magentaBright = "#c6acfa"
cyanBright = "#74dbcb"
