[colors.roles]
text = "#dddddd"
textSecondary = "#dddddd99"
background = "#4b4b4b"
surface = "#dddddd0d"
border = "#dddddd38"
puzzleBorder = "#dddddd"
puzzleInnerBorder = "#dddddd38"
blue = "#97bdde"
red = "#e388a3"
green = "#98bd99"
yellow = "#ffdf9b"

[colors.regions]
red = "#e388a3"
green = "#98bd99"
yellow = "#ffdf9b"
blue = "#97bdde"
magenta = "#a5a6c5"
cyan = "#6fbdbe"
redBright = "#eb99b1"
greenBright = "#8fcd92"
yellowBright = "#ffe5b3"
blueBright = "#a2c8e9"
magentaBright = "#b2b3da"
cyanBright = "#6bcacb"
