[colors.roles]
text = "#e1d4d4"
textSecondary = "#e1d4d499"
background = "#1a1825"
surface = "#e1d4d40d"
border = "#e1d4d438"
puzzleBorder = "#e1d4d4"
puzzleInnerBorder = "#e1d4d438"
blue = "#9ccfd8"
red = "#eb7193"
green = "#317490"
yellow = "#f6c074"

[colors.regions]
red = "#eb7193"
green = "#317490"
yellow = "#f6c074"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#9ccfd8"
redBright = "#f289a4"
greenBright = "#358daf"
yellowBright = "#f9ca8e"
blueBright = "#94dae6"
magentaBright = "#ceb3ef"
cyanBright = "#94dae6"
