[colors.roles]
text = "#4f5b62"
textSecondary = "#4f5b62b3"
background = "#faf3e1"
surface = "#faf3e1"
border = "#4f5b622e"
puzzleBorder = "#4f5b62"
puzzleInnerBorder = "#4f5b62b3"
blue = "#3a94c4"
red = "#f85550"
green = "#8da200"
yellow = "#dea000"

[colors.regions]
red = "#f85550"
green = "#8da200"
yellow = "#dea000"
blue = "#3a94c4"
magenta = "#df69ba"
cyan = "#36a87e"
redBright = "#e6271c"
greenBright = "#758700"
yellowBright = "#b98500"
blueBright = "#297ca6"
magentaBright = "#ca43a3"
cyanBright = "#258c67"
