[colors.roles]
text = "#353535"
textSecondary = "#353535b3"
background = "#eeeeee"
surface = "#eeeeee"
border = "#3535352e"
puzzleBorder = "#353535"
puzzleInnerBorder = "#353535b3"
blue = "#286486"
red = "#a8334c"
green = "#4f6c31"
yellow = "#944927"

[colors.regions]
red = "#a8334c"
green = "#4f6c31"
yellow = "#944927"
blue = "#286486"
magenta = "#88507d"
cyan = "#3b8992"
redBright = "#94253e"
greenBright = "#3f5a22"
yellowBright = "#803d1c"
blueBright = "#1d5573"
magentaBright = "#7b3b70"
cyanBright = "#2b747c"
