[colors.roles]
text = "#724341"
textSecondary = "#724341b3"
background = "#fbf6f0"
surface = "#fbf6f0"
border = "#7243412e"
puzzleBorder = "#724341"
puzzleInnerBorder = "#724341b3"
blue = "#5795a0"
red = "#b5637a"
green = "#286a84"
yellow = "#ec9d33"

[colors.regions]
red = "#b5637a"
green = "#286a84"
yellow = "#ec9d33"
blue = "#5795a0"
magenta = "#917ba9"
cyan = "#5795a0"
redBright = "#a54a66"
greenBright = "#1c5970"
yellowBright = "#c68223"
blueBright = "#407d88"
magentaBright = "#855aac"
cyanBright = "#407d88"
