[colors.roles]
text = "#e7dcc4"
textSecondary = "#e7dcc499"
background = "#2c343a"
surface = "#e7dcc40d"
border = "#e7dcc438"
puzzleBorder = "#e7dcc4"
puzzleInnerBorder = "#e7dcc438"
blue = "#7fbcb4"
red = "#e67c7f"
green = "#a9c181"
yellow = "#ddbd7f"

[colors.regions]
red = "#e67c7f"
green = "#a9c181"
yellow = "#ddbd7f"
blue = "#7fbcb4"
magenta = "#d69ab7"
cyan = "#83c193"
redBright = "#ed9294"
greenBright = "#b0ce7b"
yellowBright = "#edc77a"
blueBright = "#7ac9c0"
magentaBright = "#e5a7c4"
cyanBright = "#7dd093"
