[colors.roles]
text = "#333a57"
textSecondary = "#333a57b3"
background = "#d6d7dc"
surface = "#d6d7dc"
border = "#333a572e"
puzzleBorder = "#333a57"
puzzleInnerBorder = "#333a57b3"
blue = "#34548c"
red = "#8b4351"
green = "#34645d"
yellow = "#8f5e14"

[colors.regions]
red = "#8b4351"
green = "#34645d"
yellow = "#8f5e14"
blue = "#34548c"
magenta = "#5a4a79"
cyan = "#176775"
redBright = "#7e3242"
greenBright = "#26554f"
yellowBright = "#794e0d"
blueBright = "#26467a"
magentaBright = "#503875"
cyanBright = "#34645d"
