[colors.roles]
text = "#c6d5cf"
textSecondary = "#c6d5cf99"
background = "#0f191f"
surface = "#c6d5cf0d"
border = "#c6d5cf38"
puzzleBorder = "#c6d5cf"
puzzleInnerBorder = "#c6d5cf38"
blue = "#8190d4"
red = "#de6e7c"
green = "#90ff6b"
yellow = "#b77e64"

[colors.regions]
red = "#de6e7c"
green = "#90ff6b"
yellow = "#b77e64"
blue = "#8190d4"
magenta = "#b279a7"
cyan = "#66a5ad"
redBright = "#e8838f"
greenBright = "#a0ff85"
yellowBright = "#d68c67"
blueBright = "#92a0e2"
magentaBright = "#cf86c1"
cyanBright = "#65b8c1"
