[colors.roles]
text = "#555555"
textSecondary = "#555555b3"
background = "#e2e2e2"
surface = "#e2e2e2"
border = "#5555552e"
puzzleBorder = "#555555"
puzzleInnerBorder = "#555555b3"
blue = "#0084a3"
red = "#dc5284"
green = "#628562"
yellow = "#c48562"

[colors.regions]
red = "#dc5284"
green = "#628562"
yellow = "#c48562"
blue = "#0084a3"
magenta = "#896788"
cyan = "#008586"
redBright = "#be3c6d"
greenBright = "#487249"
yellowBright = "#a76b48"
blueBright = "#006f89"
magentaBright = "#7f4c7e"
cyanBright = "#006f70"
